/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DescobrirRouteImport } from './routes/descobrir'
import { Route as BuscarRouteImport } from './routes/buscar'
import { Route as BibliotecaRouteImport } from './routes/biblioteca'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LivroSlugRouteImport } from './routes/livro.$slug'

const DescobrirRoute = DescobrirRouteImport.update({
  id: '/descobrir',
  path: '/descobrir',
  getParentRoute: () => rootRouteImport,
} as any)
const BuscarRoute = BuscarRouteImport.update({
  id: '/buscar',
  path: '/buscar',
  getParentRoute: () => rootRouteImport,
} as any)
const BibliotecaRoute = BibliotecaRouteImport.update({
  id: '/biblioteca',
  path: '/biblioteca',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LivroSlugRoute = LivroSlugRouteImport.update({
  id: '/livro/$slug',
  path: '/livro/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/biblioteca': typeof BibliotecaRoute
  '/buscar': typeof BuscarRoute
  '/descobrir': typeof DescobrirRoute
  '/livro/$slug': typeof LivroSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/biblioteca': typeof BibliotecaRoute
  '/buscar': typeof BuscarRoute
  '/descobrir': typeof DescobrirRoute
  '/livro/$slug': typeof LivroSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/biblioteca': typeof BibliotecaRoute
  '/buscar': typeof BuscarRoute
  '/descobrir': typeof DescobrirRoute
  '/livro/$slug': typeof LivroSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/biblioteca' | '/buscar' | '/descobrir' | '/livro/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/biblioteca' | '/buscar' | '/descobrir' | '/livro/$slug'
  id:
    | '__root__'
    | '/'
    | '/biblioteca'
    | '/buscar'
    | '/descobrir'
    | '/livro/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BibliotecaRoute: typeof BibliotecaRoute
  BuscarRoute: typeof BuscarRoute
  DescobrirRoute: typeof DescobrirRoute
  LivroSlugRoute: typeof LivroSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/descobrir': {
      id: '/descobrir'
      path: '/descobrir'
      fullPath: '/descobrir'
      preLoaderRoute: typeof DescobrirRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buscar': {
      id: '/buscar'
      path: '/buscar'
      fullPath: '/buscar'
      preLoaderRoute: typeof BuscarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/biblioteca': {
      id: '/biblioteca'
      path: '/biblioteca'
      fullPath: '/biblioteca'
      preLoaderRoute: typeof BibliotecaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/livro/$slug': {
      id: '/livro/$slug'
      path: '/livro/$slug'
      fullPath: '/livro/$slug'
      preLoaderRoute: typeof LivroSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BibliotecaRoute: BibliotecaRoute,
  BuscarRoute: BuscarRoute,
  DescobrirRoute: DescobrirRoute,
  LivroSlugRoute: LivroSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
